import TopMenuBlock from "@/components/TopMenuBlock/TopMenuBlock"
import Head from "next/head"
import Link from "next/link"
import React from "react"

import styles from '../styles/taspp.module.scss'

const TermsOfService: React.FC = () => {
    return(
        <>
            <Head>
                <title>HomEazyAi | Terms Of Service</title>
            </Head>
            <TopMenuBlock isPrivacy />
            <div className={styles.infoWrapper}>
                <h1>Terms Of Service</h1>
                <h2>Version Effective Date: January 20, 2022</h2>
                Thank you for using HomEazyAI chat generation and chat services (the “Services”). These Terms of Service 
                (the “Agreement”) spell out what rights you have with respect to the Service generated images, and other assets, 
                which you generate (the “Assets”), your use of the Services, and other important topics like arbitration. Please read it carefully. 
                We have a privacy policy which outlines how we handle your data <Link href={'/privacy-policy'}>here</Link>.<br/><br/>

                This Agreement is entered into by HomEazyAI and the entity or person agreeing to these terms (“Customer”) and 
                govern Customer{`'`}s access to and use of the Services. <br/><br/>
                
                This Agreement is effective when the Customer is presented with this Agreement and proceeds to use the Services (the “Effective Date”) 
                or to receive or distribute Assets. These terms may be updated and presented again to the Customer from time to time. 
                Continued use of the Services constitutes acceptance of the updated terms. If you do not agree to the Agreement, please stop using the Services. <br/><br/>

                Other documents referenced here may also bind Customer’s use of this Services, including the Community Guidelines included below. <br/><br/>

                <h1>1. Service Availability and Quality</h1>

                We are constantly evolving the Services to make them better for you. 
                The Services are subject to modification and change, including but not limited to the art style of Assets, 
                the algorithms used to generate the Assets, and features available to the Customer. 
                No guarantees are made with respect to the Services’ quality, stability, uptime or reliability. 
                Please do not create any dependencies on any attributes of the Services or the Assets. We will not be liable to you or your 
                downstream customers for any harm caused by your dependency on the Service. <br/><br/>

                Both the Services and the Assets are provided to Customer on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
                either express or implied, including, without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, 
                or FITNESS FOR A PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing 
                the Assets and assume any risks associated with use of the Services.<br/><br/>

                HomEazyAI reserves the right to suspend or ban your access to the Services at any time, and for any reason. You may not use the Services for 
                competitive research. You may not reverse engineer the Services or the Assets. You may not use automated tools to access, interact with, 
                or generate Assets through the Services. Only one user may use the Services per registered account. Each user of the Services may only have one account. <br/><br/>

                <h1>2. Age Requirements</h1>

                By accessing the Services, you confirm that you’re at least 13 years old and meet the minimum age of digital consent in your country. 
                If you are old enough to access the Services in your country, but not old enough to have authority to consent to our terms, 
                your parent or guardian must agree to our terms on your behalf. <br/><br/>

                Please ask your parent or guardian to read these terms with you. If you’re a parent or legal guardian, and you allow your teenager to use the Services, then 
                these terms also apply to you and you’re responsible for your teenager’s activity on the Services. <br/><br/>

                HomEazyAI tries to make its Services PG-13 and family friendly, but the Assets are generated by an artificial intelligence system based on user queries. This is new technology and it does not always work as expected. 
                No guarantees are made as to the suitability of the Assets for the Customer. <br/><br/>

                <h1>3. Your Information</h1>

                By using the Services, you may provide HomEazyAI with personal information like your email address, user name, billing information, 
                favorites, image outputs, and text prompts that you enter, or sample images that you upload to the Service. 
                Our policy outlining what we do with your personal information, and the rights you have with respect to your personal information, 
                can be found here. Both parties agree to comply with all applicable data protection laws. 
                To the extent the parties need to enter into additional terms regarding data privacy or data transfers the parties will work 
                together in good faith to enter into such terms.<br/><br/>

                <h1>4. Copyright and Trademark</h1>

                In this section, Paid Member shall refer to a Customer who has subscribed to the latest Phase 3 payment plan, which became available as of 8/9/22. <br/><br/>

                <b>Rights you give to</b> HomEazyAI <br/><br/>

                By using the Services, you grant to HomEazyAI its successors, and assigns a perpetual, worldwide, non-exclusive, sublicensable no-charge, 
                royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, 
                and distribute text, and image prompts you input into the Services, or Assets produced by the service at your direction. This license survives 
                termination of this Agreement by any party, for any reason. <br/><br/>

                <b>Your Rights</b>

                Subject to the above license, you own all Assets you create with the Services. This does not apply if you fall under the exceptions below. <br/><br/>

                Please note: HomEazyAI is an open community which allows others to use and remix your images and prompts whenever they are posted in a public setting. By default, your images are publically viewable and remixable. As described above, you grant HomEazyAI a license to allow this. 
                If you purchase a private plan, you may bypass some of these public sharing defaults. <br/><br/>

                <b>Exception 2: Corporate-User License Terms</b>

                If you are an employee or owner of a company with more than $1,000,000 USD a year in gross revenue, and you are using the Services to benefit your Employer or company you must purchase a 
                corporate membership plan to use the Services or copy the Assets for your company.<br/><br/>

                Corporate membership plans involve an upfront, non-refundable deposit for up to 12 months of service. <br/><br/>

                <b>Exception 3: Asset Privacy</b>

                If you are subject to a corporate license, or bought a privacy add-on to your subscription, 
                we agree to make best efforts not to publish any Assets you make in any situation where “Private mode” is engaged in the Services.<br/><br/>

                Please be aware that any image you make in a shared or open space such as a Discord chatroom, is viewable by anyone in that chatroom, 
                regardless of whether Private mode is engaged.<br/><br/>

                <h1>5. DMCA and Takedowns Policy</h1>

                HomEazyAI uses an artificial intelligence system trained on public datasets to produce its Assets. 
                Such Assets may be unintentionally similar to copyright protected material or trademarks you hold. We respect rights holders internationally. 
                If you believe your copyright or trademark is being infringed by the Service, please write to aiprojectionshelp@gmail.com and we will process your request.<br/><br/>

                <h1>6. Dispute Resolution and Governing Law</h1>

                <ol type="1">
                    <li>ALL LEGAL CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT (INCLUDING ANY DISPUTE REGARDING THE INTERPRETATION OR PERFORMANCE OF THE AGREEMENT) (“Dispute”) WILL BE GOVERNED BY THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING CALIFORNIA{`'`}S CONFLICTS OF LAWS RULES. Sorry for putting that in caps, but hopefully you read it carefully. We{`'`}re talking about serious and reasonably meritorious legal claims, not personal disputes that don{`'`}t cause economic harm.</li>
                    <li>The parties will try in good faith to settle any Dispute within 30 days after the Dispute arises. If the Dispute is not resolved within 30 days, it shall be resolved by arbitration by the American Arbitration Association’s International Centre for Dispute Resolution in accordance with its Expedited Commercial Rules in force as of the date of this Agreement (“Rules”).
                        The parties will mutually select one arbitrator. The arbitration will be conducted in English in Santa Clara County, California, USA.</li>
                    <li>Either party may apply to any competent court for injunctive relief necessary to protect its rights pending resolution of the arbitration. The arbitrator may order equitable or injunctive relief consistent with the remedies and limitations in the Agreement.</li>
                    <li>The arbitral award will be final and binding on the parties and its execution may be presented in any competent court, including any court with jurisdiction over either party or any of its property.</li>
                    <li>Each party will bear its own lawyers’ and experts’ fees and expenses, regardless of the arbitrator’s final decision regarding the Dispute.</li>
                </ol> 

                <h1>7. Payment and Billing</h1>

                We may invoice you for your use of the Services through a third party payment service provider. The third party service provider’s terms of service shall govern and supersede this Agreement in case of conflict. <br/><br/>
                You are free to cancel your plan at any time. We also reserve the right to terminate your access to the Service for any reason, including for violation of the Community Guidelines or other inappropriate use of the Service. Upon cancellation or termination, any outstanding usage fees will be charged immediately. You will not be refunded for the current pay period, but you will stop being charging after the current pay period has ended.<br/><br/>

                <h1>8. Community Guidelines</h1>
                <ol type="1">
                    <li>Be kind and respect each other and staff. Do not create images or use text prompts that are inherently disrespectful, aggressive, or otherwise abusive. Violence or harassment of any kind will not be tolerated.</li>
                    <li>No adult content or gore. Please avoid making visually shocking or disturbing content. We will block some text inputs automatically.</li>
                    <li>Sharing others’ creations. Do not publicly repost the creations of others without their permission.</li>
                    <li>Be careful about sharing. It’s OK to share your creations outside of the Midjourney community but please consider how others might view your content.</li>
                    <li>Banhammer. Any violations of these rules may lead to bans from our services. We are not a democracy. Behave respectfully or lose your rights to use the Service.</li>
                </ol> 

                <h1>9. Limitation of Liability and Indemnity</h1>

                We provide the service as is, and we make no promises or guarantees about it. <br/><br/>
                You understand and agree that we will not be liable to you or any third party for any loss of profits, use, goodwill, or data, or for any incidental, indirect, special, consequential or exemplary damages, however they arise.<br/><br/>
                You are responsible for your use of the service. If you harm someone else or get into a dispute with someone else, we will not be involved.<br/><br/>
                If you knowingly infringe someone else’s intellectual property, and that costs us money, we’re going to come find you and collect that money from you. We might also do other stuff, like try to get a court to make you pay our attorney’s fees. Don’t do it.<br/><br/>

                <h1>10. Miscellaneous</h1>
                <ol type="1">
                    <li>Force Majeure. Neither party will be liable for failure or delay in performance to the extent caused by circumstances beyond its reasonable control, including acts of God, natural disasters, terrorism, riots, or war.</li>
                    <li>No Agency. This Agreement does not create any agency, partnership, or joint venture between the parties.</li>
                    <li>Severability. If any part of this Agreement is invalid, illegal, or unenforceable, the rest of the Agreement will remain in effect.</li>
                    <li>No Third-Party Beneficiaries. This Agreement does not confer any benefits on any third party unless it expressly states that it does.</li>
                    <li>Survival. The sections and obligations in this Agreement that a reasonable person would expect to survive this agreement, will. Particularly the IP and privacy stuff</li>
                </ol>

            </div>
        </>
    )
}

export default TermsOfService